services:
  helldivers2-democracy-hub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: helldivers2-democracy-hub
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - helldivers2-network

networks:
  helldivers2-network:
    driver: bridge
