name: "Build and Deploy to Azure Container Apps"

env:
  AZURE_CONTAINER_REGISTRY: helldivers2acr8624  # Our actual ACR name
  CONTAINER_NAME: helldivers2-democracy-hub
  RESOURCE_GROUP: rg-helldivers2-democracy-hub-20250809  # Our actual resource group
  CONTAINER_APP_NAME: helldivers2-democracy-hub
  CONTAINER_APP_ENVIRONMENT: helldivers2-env
  TARGET_PORT: 5000  # Our app runs on port 5000, not 8080

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build and push container image to registry
      uses: azure/container-apps-deploy-action@v2
      with:
        appSourcePath: ${{ github.workspace }}
        registryUrl: ${{ secrets.ACR_LOGIN_SERVER }}
        registryUsername: ${{ secrets.ACR_USERNAME }}
        registryPassword: ${{ secrets.ACR_PASSWORD }}
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
        imageToBuild: ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
        dockerfilePath: Dockerfile
        targetPort: ${{ env.TARGET_PORT }}
        environmentVariables: 'ASPNETCORE_ENVIRONMENT=Production ASPNETCORE_URLS=http://*:5000 ASPNETCORE_HTTP_PORTS=5000'
